BlogReceita/BlogReceita/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('blog.urls')),
    url(r'^accounts/login/$', views.login, name='login'),
    url(r'^accounts/logout/$', views.logout, name='logout', kwargs={'next_page': '/'}),
]

BlogReceita/blog/urls.py
from django.conf.urls import url
from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.receita_lista, name='receita_lista'),
    url(r'^receita/(?P<pk>[0-9]+)/$', views.receita_detalhe, name='receita_detalhe'),
    url(r'^receita/new/$', views.nova_receita, name='nova_receita'),
    url(r'^receita/(?P<pk>[0-9]+)/editar/$', views.editar_receita, name='editar_receita'),
    url(r'^receita/(?P<pk>\d+)/publicar/$', views.publicar_receita, name='publicar_receita'),
    url(r'^receita/(?P<pk>\d+)/remover/$', views.remover_receita, name='remover_receita'),
    url(r'^receita/(?P<pk>\d+)/comentario/$', views.add_comentario_a_receita, name='add_comentario_a_receita'),
    url(r'^rascunhos/$', views.rascunhos, name='rascunhos'),
    url(r'^comentario/(?P<pk>\d+)/aprovar/$', views.aprovar_comentario, name='aprovar_comentario'),
    url(r'^comentario/(?P<pk>\d+)/remover/$', views.remover_comentario, name='remover_comentario'),
]

BlogReceita/blog/models.py
from django.db import models

from django.utils import timezone
# Create your models here.


class Receita(models.Model):
    autor = models.ForeignKey('auth.User')
    titulo = models.CharField(max_length=200)
    tempo_preparo = models.TimeField(verbose_name='Tempo de preparo')
    rendimento = models.IntegerField(verbose_name='Rendimento')
    ingredientes = models.TextField()
    modo_preparo = models.TextField(verbose_name='Modo de preparo')
    data_criacao = models.DateTimeField(default=timezone.now)
    data_publicacao = models.DateTimeField(blank=True, null=True)

    def publicar(self):
        self.data_publicacao = timezone.now()
        self.save()

    def aprovar_comentario(self):
        return self.comentarios.filter(comentario_aprovado=True) # Esse 'comentarios' é o related_name da variável 'receitas' na Classe 'Comentários'

    def __str__(self):
        return self.titulo


class Comentario(models.Model):
    receita = models.ForeignKey('blog.Receita', related_name='comentarios')
    autor = models.CharField(max_length=200)
    comentario = models.TextField()
    data_criacao = models.DateTimeField(default=timezone.now)
    comentario_aprovado = models.BooleanField(default=False)

    def aprovar(self):
        self.comentario_aprovado = True
        self.save()

    def __str__(self):
        return self.comentario

BlogReceita/blog/forms.py
from django import forms
from .models import Receita, Comentario


class ReceitaForm(forms.ModelForm):
    class Meta:
        model = Receita
        fields = ('titulo', 'tempo_preparo', 'rendimento', 'ingredientes', 'modo_preparo',)


class ComentarioForm(forms.ModelForm):
    class Meta:
        model = Comentario
        fields = ('autor', 'comentario',)

BlogReceita/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.contrib.auth.decorators import login_required

from .models import *
from .forms import *
# Create your views here.


def receita_detalhe(request, pk):
    receita = get_object_or_404(Receita, pk=pk)
    return render(request, 'blog/receita_detalhe.html', {'receita': receita})


def receita_lista(request):
    receitas = Receita.objects.filter(data_publicacao__lte=timezone.now()).order_by('data_publicacao')
    return render(request, 'blog/receita_lista.html', {'receitas': receitas})


@login_required
def nova_receita(request):
    if request.method == 'POST':
        formulario = ReceitaForm(request.POST)
        if formulario.is_valid():
            receita = formulario.save(commit=False)
            receita.autor = request.user
            #receita.data_publicacao = timezone.now()
            receita.save()
            return redirect('blog:receita_detalhe', pk=receita.pk)
    else:
        formulario = ReceitaForm()
    return render(request, 'blog/editar_receita.html', {'formulario': formulario})


@login_required
def editar_receita(request, pk):
    receita = get_object_or_404(Receita, pk=pk)
    if request.method == "POST":
        formulario = ReceitaForm(request.POST, instance=receita)
        if formulario.is_valid():
            receita = formulario.save(commit=False)
            receita.autor = request.user
            receita.published_date = timezone.now()
            receita.save()
            return redirect('blog:post_detail', pk=receita.pk)
    else:
        formulario = ReceitaForm(instance=receita)
    return render(request, 'blog/editar_receita.html', {'formulario': formulario})


@login_required
def rascunhos(request):
    receitas = Receita.objects.filter(data_publicacao__isnull=True).order_by('data_criacao')
    return render(request, 'blog/rascunhos.html', {'receitas': receitas})


@login_required
def publicar_receita(request, pk):
    receita = get_object_or_404(Receita, pk=pk)
    receita.publicar()
    return redirect("blog:receita_detalhe", pk=receita.pk)


@login_required
def remover_receita(request, pk):
    receita = get_object_or_404(Receita, pk=pk)
    receita.delete()
    return redirect('blog:receita_lista')


def add_comentario_a_receita(request, pk):
    receita = get_object_or_404(Receita, pk=pk)
    if request.method == 'POST':
        formulario = ComentarioForm(request.POST)
        if formulario.is_valid():
            comentario = formulario.save(commit=False)
            comentario.receita = receita
            comentario.save()
            return redirect('blog:receita_detalhe', pk=receita.pk)
    else:
        formulario = ComentarioForm()
    return render(request, 'blog/add_comentario_a_receita.html', {'formulario': formulario})


@login_required
def aprovar_comentario(request, pk):
    comentario = get_object_or_404(Comentario, pk=pk)
    comentario.aprovar()
    return redirect('blog:receita_detalhe', pk=comentario.receita.pk)


@login_required
def remover_comentario(request, pk):
    comentario = get_object_or_404(Comentario, pk=pk)
    comentario.delete()
    return redirect('blog:receita_detalhe', pk=comentario.receita.pk)


def mostra_todas(request):
    receitas = Receita.objects.all()
    titulos = []
    for titulo in receitas:
        titulos.append(titulo.titulo)
    return titulos

BlogReceita/blog/templates/blog/add_comentario_a_receita.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1>Novo comentário</h1>
    <form method="POST" class="post-form">
        {% csrf_token %}
        {{ formulario.as_p }}
        <button type="submit" class="save btn btn-default"><span class="glyphicon glyphicon-floppy-save">Comentário</span></button>
    </form>
{% endblock %}

BlogReceita/blog/templates/blog/base.html
{% load staticfiles %}
<html lang="pt-br">
    <head>
        <title>Blog Sua Receita</title>
        <meta charset="UTF-8">
        <link href="https://fonts.googleapis.com/css?family=Cinzel|Dancing+Script|Great+Vibes" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
        <script src="{% static 'js/jquery-3.2.1.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
    </head>
    <body>
        <div class="page-header">
            {% if user.is_authenticated %}
                <a href="{% url 'blog:nova_receita' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
                <a href="{% url 'blog:rascunhos' %}" class="top-menu"><span class="glyphicon glyphicon-edit"></span></a>
                <p class="top-menu">Olá {{ user.username }} <small>(<a href="{% url 'logout' %}">Sair</a>)</small></p>
            {% else %}
                <a href="{% url 'login' %}" class="top-menu"><span class="glyphicon glyphicon-lock"></span></a>
            {% endif %}
            <h1><a href="/">Sua Receita</a></h1>
            <p id="slogan">O seu blog de culinária.</p>
        </div>
           <div class="content container">
            <div class="row">
                <div class="col-md-12">
                    <p>
                    {% block content %}
                    {% endblock %}
                    </p>
                </div>
            </div>
        </div>

    <footer> <!-- Aqui e a area do footer -->
        <div class="container">
          <div class="row">

   			<div id="linksImportantes" class="col-md-3">
	    		<h4>Mais Receitas para você</h4>
		    		<ul>
						<li><a href="http://mdemulher.abril.com.br/receitas/">M de Mulher</a></li>
                        <li><a href="http://www.tudogostoso.com.br/">Tudo Gostoso</a></li>
                        <li><a href="http://anamariabraga.globo.com/receitas">Receitas da Ana</a></li>
                        <li><a href="http://www.sadia.com.br/receitas">Receitas Sadia</a></li>
                        <li><a href="http://receitas.eduguedes.com.br/">Receitas Edu Guedes</a></li>
					</ul>
			</div> <!-- Aqui e a area dos links importantes -->


            <div id="redesSociais" class="col-md-3">
              <h4>Redes Sociais</h4>
              <ul>
                <li><a href="https://www.facebook.com/jbarsan">Facebook</a></li>
                <li><a href="https://plus.google.com/u/0/+Jo%C3%A3oCarlosBarbosadosSantos">Googleplus</a></li>
                <li><a href="https://twitter.com/joao_barsan">Twitter</a></li>
              </ul>
            </div> <!-- Aqui e a area das redes sociais -->
            <div id="logoFooter" class="col-md-offset-3 col-md-3">
              <h2><a href="/">Sua Receita</a></h2>
            </div> <!-- Aqui e a area da logo do rodape -->
          </div>
        </div>
      </footer>

        <div class="copyright">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<span class="glyphicon glyphicon-registration-mark"> Todos os direitos reservados.</span>
					</div>
				</div>
			</div>
		</div>


    </body>
</html>

BlogReceita/blog/templates/blog/base_teste.html
{% load staticfiles %}
<html lang="pt-br">
    <head>
        <title>Blog Sua Receita</title>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/estilo.css' %}">
        <script src="{% static 'js/jquery-3.2.1.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
        <link href="https://fonts.googleapis.com/css?family=Dancing+Script" rel="stylesheet">
        <!-- <link rel="stylesheet" href="{% static 'css/blog.css' %}"> -->
    </head>
    <body>


      <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="row">
                <div class="page-header"></div>
                {% if user.is_authenticated %}
                    <a href="{% url 'blog:nova_receita' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
                    <a href="{% url 'blog:rascunhos' %}" class="top-menu"><span class="glyphicon glyphicon-edit"></span></a>
                    <p class="top-menu">Olá {{ user.username }} <small>(<a href="{% url 'logout' %}">Sair</a>)</small></p>
                {% else %}
                    <a href="{% url 'login' %}" class="top-menu"><span class="glyphicon glyphicon-lock"></span></a>
                {% endif %}
                    <h1><a href="/">Blog Sua Receita</a></h1>
                </div>
            </div>

        </div>
      </nav>

      <div class="wrapper" role="main">
        <div class="content container">
          <div class="row">
            <div id="conteudo" class="col-xs-12 col-sm-8 col-md-9">
              <div class="artigo" role="article">
                <div class="row">
                  <div class="col-xs-12 col-sm-4 col-md-4">
                    <!--<a href="#" title="">-->
                      <!--<img src="http://placehold.it/350x350" alt="">-->
                    <!--</a>-->
                  </div>
                  <div class="col-xs-12 col-sm-8 col-md-8">
                    <p>
                      {% block content %}
                      {% endblock %}
                    </p>
                  </div>
                </div><!-- div row conteudo -->
              </div> <!-- div artigo -->
            </div><!-- div conteudo -->

            <!-- Sidebar -->
            <div id="sidebar" class="col-xs-12 col-sm-4 col-md-3">
              <div class="widget">
                <h3>Parceiros</h3>
                <ul>
                  <li><a href="http://mdemulher.abril.com.br/receitas/">M de Mulher</a></li>
                  <li><a href="http://www.tudogostoso.com.br/">Tudo Gostoso</a></li>
                  <li><a href="http://anamariabraga.globo.com/receitas">Receitas da Ana</a></li>
                  <li><a href="http://www.sadia.com.br/receitas">Receitas Sadia</a></li>
                  <li><a href="http://receitas.eduguedes.com.br/">Receitas Edu Guedes</a></li>
                </ul>
              </div>
            </div>

          </div><!-- div row container -->
        </div><!-- div container -->
      </div><!-- div wrapper -->

      <footer> <!-- Aqui e a area do footer -->
        <div class="container">
          <div class="row">

   			<div id="linksImportantes" class="col-md-3">
	    		<h4>Links Importantes</h4>
		    		<ul>
						<li><a href="#">Link1</a></li>
						<li><a href="#">Link2</a></li>
						<li><a href="#">Link3</a></li>
						<li><a href="#">Link4</a></li>
					</ul>
			</div> <!-- Aqui e a area dos links importantes -->


            <div id="redesSociais" class="col-md-3">
              <h4>Redes Sociais</h4>
              <ul>
                <li><a href="https://www.facebook.com/jbarsan">Facebook</a></li>
                <li><a href="https://plus.google.com/u/0/+Jo%C3%A3oCarlosBarbosadosSantos">Googleplus</a></li>
                <li><a href="https://twitter.com/joao_barsan">Twitter</a></li>
              </ul>
            </div> <!-- Aqui e a area das redes sociais -->
            <div id="logoFooter" class="col-md-offset-3 col-md-3">
              <h2>Sua Receita</h2>
            </div> <!-- Aqui e a area da logo do rodape -->
          </div>
        </div>
      </footer>

        <div class="copyright">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p>&copy; Todos os direitos reservados.</p>
					</div>
				</div>
			</div>
		</div>

    </body>
</html>

BlogReceita/blog/templates/blog/editar_receita.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1>Nova Receita</h1>
    <form method="POST" class="post-form">
        {% csrf_token %}
        {{ formulario.as_p }}
        <button type="submit" class="save btn btn-default">Guardar</button>
    </form>
{% endblock %}

BlogReceita/blog/templates/blog/rascunhos.html
{% extends 'blog/base.html' %}

{% block content %}
    {% for receita in receitas %}
        <div class="post">
            <p class="date">Criado: {{ receita.data_criacao|date:'d-m-Y' }}</p>
            <h1><a href="{% url 'blog:receita_detalhe' pk=receita.pk %}">{{ receita.titulo }}</a></h1>
            <p><em>Tempo de preparo: {{ receita.tempo_preparo }}</em></p>
            <p><em>Rendimento: {{ receita.rendimento }}</em></p>
            <h3>Ingredientes</h3>
            <p>{{ receita.ingredientes|linebreaksbr }}</p>
            <!--<p>{{ receita.ingredientes|truncatechars:200 }}</p>-->
            <h3>Modo de preparo</h3>
            <p>{{ receita.modo_preparo|linebreaksbr }}</p>
        </div>
    {% endfor %}
{% endblock %}

BlogReceita/blog/templates/blog/receita_detalhe.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="post">
        {% if receita.data_publicacao %}
            <div class="date">
                {{ receita.data_publicacao }}
            </div>
        {% else %}
            <a class="btn btn-default" href="{% url 'blog:publicar_receita' pk=receita.pk %}">Publicar</a>
        {% endif %}

        {% if user.is_authenticated %}
            <a class="btn btn-default" href="{% url 'blog:editar_receita' pk=receita.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
            <a class="btn btn-default" href="{% url 'blog:remover_receita' pk=receita.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
        {% else %}
            <a href="{% url 'login' %}" class="top-menu"><span class="glyphicon glyphicon-lock"></span></a>
        {% endif %}
        <h1>{{ receita.titulo }}</h1>
        <p><em>Tempo de preparo: {{ receita.tempo_preparo }}</em></p>
        <p><em>Rendimento: {{ receita.rendimento }}</em></p>
        <h3>Ingredientes</h3>
        <p>{{ receita.ingredientes|linebreaksbr }}</p>
        <h3>Modo de preparo</h3>
        <p>{{ receita.modo_preparo|linebreaksbr }}</p>

    </div>

    <hr>
    <a class="btn btn-default" href="{% url 'blog:add_comentario_a_receita' pk=receita.pk %}">Adicionar Comentário</a>
    {% for comentario in receita.comentarios.all %}
        {% if user.is_authenticated or comentario.comentario_aprovado %}
            <div class="comment">
                <div class="date">
                    {{ comentario.data_criacao }}
                    {% if not comentario.comentario_aprovado %}
                        <a class="btn btn-default" href="{% url 'blog:remover_comentario' pk=comentario.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
                        <a class="btn btn-default" href="{% url 'blog:aprovar_comentario' pk=comentario.pk %}"><span class="glyphicon glyphicon-ok"></span></a>
                    {% endif %}
                </div>
                <strong>{{ comentario.autor }}</strong>
                <p>{{ comentario.comentario|linebreaks }}</p>
            </div>
        {% endif %}
    {% empty %}
        <p>Sem comentários ainda :(</p>
    {% endfor %}
{% endblock %}

BlogReceita/blog/templates/blog/receita_lista.html
{% extends 'blog/base.html' %}

{% block content %}
    {% for receita in receitas %}
        <div class="post">
            <div class="date">
                {{ receita.data_publicacao }}
            </div>
            <h1><a href="{% url 'blog:receita_detalhe' pk=receita.pk %}">{{ receita.titulo }}</a></h1>
            <p><em>Tempo de preparo: {{ receita.tempo_preparo }}</em></p>
            <p><em>Rendimento: {{ receita.rendimento }}</em></p>
            <h3>Ingredientes</h3>
            <p>{{ receita.ingredientes|linebreaksbr }}</p>
            <h3>Modo de preparo</h3>
            <p>{{ receita.modo_preparo|linebreaksbr }}</p>
            <a href="{% url 'blog:receita_detalhe' pk=receita.pk %}">Comentários: {{ receita.comentarios.count }}</a>
        </div>
    {% endfor %}
{% endblock content %}

BlogReceita/blog/templates/blog/teste.html
{% load staticfiles %}
<html lang="pt-br">
    <head>
        <title>Blog Sua Receita</title>
        <meta charset="UTF-8">
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="{% static 'css/blog2.css' %}">
    </head>
    <body>
        <div class="page-header">
            {% if user.is_authenticated %}
                <a href="{% url 'blog:nova_receita' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
                <a href="{% url 'blog:rascunhos' %}" class="top-menu"><span class="glyphicon glyphicon-edit"></span></a>
                <p class="top-menu">Olá {{ user.username }} <small>(<a href="{% url 'logout' %}">Sair</a>)</small></p>
            {% else %}
                <a href="{% url 'login' %}" class="top-menu"><span class="glyphicon glyphicon-lock"></span></a>
            {% endif %}
            <h1><a href="/">Blog Sua Receita</a></h1>
        <main>
        </div>
           <div class="content container">
            <div class="row">
                <div class="col-md-8">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
      </main>
        <footer id="footer">
    			<div class="innertube">
    				<p>Desenvolvido por João Carlos Barsan</p>
    			</div>
    		</footer>
    </body>
</html>